/**
 * Demo Data for NatID CRM
 * Comprehensive mock data for all entity types.
 * All dates are relative to current time for freshness.
 */

// Date helpers
const now = new Date();
function daysAgo(n) {
  const d = new Date(now);
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
function hoursAgo(n) {
  const d = new Date(now);
  d.setHours(d.getHours() - n);
  return d.toISOString();
}
function minutesAgo(n) {
  const d = new Date(now);
  d.setMinutes(d.getMinutes() - n);
  return d.toISOString();
}
function daysFromNow(n) {
  const d = new Date(now);
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

// Demo admin user
export const demoUser = {
  id: "demo_user_admin",
  email: "admin@natid-demo.com",
  full_name: "אבי כהן",
  role: "admin",
  is_active: true,
  profile_image: null,
};

// ===== CUSTOMERS =====
const customers = [
  {
    id: "demo_customer_1",
    name: "הראל ביטוח",
    customer_type: "insurance_company",
    contact_person: "רונית כהן",
    phone: "03-5123456",
    email: "service@harel-demo.co.il",
    address: "שדרות אבא הלל 13",
    city: "רמת גן",
    contract_type: "monthly",
    sla_response_minutes: 30,
    sla_arrival_minutes: 45,
    monthly_budget: 50000,
    status: "active",
    created_date: daysAgo(180),
  },
  {
    id: "demo_customer_2",
    name: "מגדל ביטוח",
    customer_type: "insurance_company",
    contact_person: "אלי לוי",
    phone: "03-5234567",
    email: "service@migdal-demo.co.il",
    address: "דרך השלום 67",
    city: "תל אביב",
    contract_type: "yearly",
    sla_response_minutes: 20,
    sla_arrival_minutes: 40,
    monthly_budget: 80000,
    status: "active",
    created_date: daysAgo(365),
  },
  {
    id: "demo_customer_3",
    name: "כלל ביטוח",
    customer_type: "insurance_company",
    contact_person: "שרה מזרחי",
    phone: "03-5345678",
    email: "service@clal-demo.co.il",
    address: "רחוב יהודה הלוי 36",
    city: "תל אביב",
    contract_type: "yearly",
    sla_response_minutes: 25,
    sla_arrival_minutes: 50,
    monthly_budget: 60000,
    status: "active",
    created_date: daysAgo(300),
  },
  {
    id: "demo_customer_4",
    name: "הפניקס ביטוח",
    customer_type: "insurance_company",
    contact_person: "נועה דהן",
    phone: "03-5678901",
    email: "service@phoenix-demo.co.il",
    address: "דרך השלום 25",
    city: "תל אביב",
    contract_type: "yearly",
    sla_response_minutes: 30,
    sla_arrival_minutes: 45,
    monthly_budget: 70000,
    status: "active",
    created_date: daysAgo(200),
  },
  {
    id: "demo_customer_5",
    name: "צי רכב — אלדן",
    customer_type: "fleet",
    contact_person: "משה פרץ",
    phone: "03-5456789",
    email: "fleet@eldan-demo.co.il",
    address: "דרך בן גוריון 1",
    city: "בני ברק",
    contract_type: "monthly",
    sla_response_minutes: 15,
    sla_arrival_minutes: 30,
    monthly_budget: 30000,
    status: "active",
    created_date: daysAgo(150),
  },
  {
    id: "demo_customer_6",
    name: "צי רכב — שלמה SIXT",
    customer_type: "fleet",
    contact_person: "דוד אברהם",
    phone: "03-5567890",
    email: "fleet@shlomo-demo.co.il",
    address: "רחוב הברזל 30",
    city: "תל אביב",
    contract_type: "monthly",
    sla_response_minutes: 20,
    sla_arrival_minutes: 35,
    monthly_budget: 45000,
    status: "active",
    created_date: daysAgo(120),
  },
  {
    id: "demo_customer_7",
    name: "מוסך גולדשטיין",
    customer_type: "garage",
    contact_person: "יעקב גולדשטיין",
    phone: "04-6123456",
    email: "info@goldstein-garage-demo.co.il",
    address: "אזור תעשייה",
    city: "חיפה",
    contract_type: "per_call",
    sla_response_minutes: 60,
    sla_arrival_minutes: 90,
    monthly_budget: 10000,
    status: "active",
    created_date: daysAgo(90),
  },
  {
    id: "demo_customer_8",
    name: "ישראל ישראלי",
    customer_type: "individual",
    contact_person: "ישראל ישראלי",
    phone: "054-1234567",
    email: "israel@demo.co.il",
    address: "רחוב הרצל 10",
    city: "תל אביב",
    contract_type: "none",
    sla_response_minutes: 60,
    sla_arrival_minutes: 90,
    monthly_budget: 0,
    status: "active",
    created_date: daysAgo(30),
  },
];

// ===== VENDORS =====
const vendors = [
  {
    id: 'demo_vendor_1',
    vendor_name: 'גרר המרכז — יוסי כהן',
    contact_person: 'יוסי כהן',
    phone: '054-7001001',
    email: 'vendor1@natid-demo.com',
    service_type: ['tow_truck'],
    vehicle_types_supported: ['private', 'commercial_light'],
    coverage_areas: ['center', 'sharon'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 32.0853,
    current_longitude: 34.7818,
    service_radius: 30,
    average_rating: 4.5,
    total_ratings: 28,
    average_response_time: 12,
    completion_rate: 0.92,
    total_calls_assigned: 145,
    works_24_7: false,
    working_hours_start: '07:00',
    working_hours_end: '23:00',
    payment_rate_per_call: 350,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'ספק ותיק ואמין, מתמחה בגרירות במרכז',
    created_date: daysAgo(365),
  },
  {
    id: 'demo_vendor_2',
    vendor_name: 'מכונאי ניידות — דוד לוי',
    contact_person: 'דוד לוי',
    phone: '054-7002002',
    email: 'vendor2@natid-demo.com',
    service_type: ['mechanic', 'tire_service'],
    vehicle_types_supported: ['private', 'commercial_light', 'motorcycle'],
    coverage_areas: ['center', 'lowlands'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 31.9635,
    current_longitude: 34.8041,
    service_radius: 25,
    average_rating: 4.8,
    total_ratings: 42,
    average_response_time: 8,
    completion_rate: 0.97,
    total_calls_assigned: 210,
    works_24_7: true,
    working_hours_start: '00:00',
    working_hours_end: '23:59',
    payment_rate_per_call: 280,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'מכונאי מעולה, עובד 24/7',
    created_date: daysAgo(400),
  },
  {
    id: 'demo_vendor_3',
    vendor_name: 'צמיגי השרון — אבי מזרחי',
    contact_person: 'אבי מזרחי',
    phone: '054-7003003',
    email: 'vendor3@natid-demo.com',
    service_type: ['tire_service'],
    vehicle_types_supported: ['private', 'commercial_light', 'truck'],
    coverage_areas: ['sharon', 'center'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 32.3215,
    current_longitude: 34.8532,
    service_radius: 20,
    average_rating: 4.2,
    total_ratings: 15,
    average_response_time: 15,
    completion_rate: 0.88,
    total_calls_assigned: 67,
    works_24_7: false,
    working_hours_start: '06:00',
    working_hours_end: '22:00',
    payment_rate_per_call: 200,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'מתמחה בצמיגים, כולל רכבים כבדים',
    created_date: daysAgo(250),
  },
  {
    id: 'demo_vendor_4',
    vendor_name: 'מנעולן 24/7 — רונן פרץ',
    contact_person: 'רונן פרץ',
    phone: '054-7004004',
    email: 'vendor4@natid-demo.com',
    service_type: ['locksmith'],
    vehicle_types_supported: ['private', 'commercial_light', 'motorcycle'],
    coverage_areas: ['center', 'sharon', 'lowlands'],
    availability_status: 'busy',
    is_active: true,
    is_available_now: false,
    current_latitude: 32.0686,
    current_longitude: 34.8248,
    service_radius: 35,
    average_rating: 4.6,
    total_ratings: 33,
    average_response_time: 10,
    completion_rate: 0.95,
    total_calls_assigned: 120,
    works_24_7: true,
    working_hours_start: '00:00',
    working_hours_end: '23:59',
    payment_rate_per_call: 320,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'מנעולן מקצועי, זמין 24/7',
    created_date: daysAgo(300),
  },
  {
    id: 'demo_vendor_5',
    vendor_name: 'גרר הצפון — משה ביטון',
    contact_person: 'משה ביטון',
    phone: '054-7005005',
    email: 'vendor5@natid-demo.com',
    service_type: ['tow_truck', 'mechanic'],
    vehicle_types_supported: ['private', 'commercial_light', 'truck'],
    coverage_areas: ['north'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 32.794,
    current_longitude: 34.9896,
    service_radius: 40,
    average_rating: 4.0,
    total_ratings: 18,
    average_response_time: 20,
    completion_rate: 0.85,
    total_calls_assigned: 78,
    works_24_7: false,
    working_hours_start: '06:00',
    working_hours_end: '21:00',
    payment_rate_per_call: 400,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'מכסה את כל אזור הצפון',
    created_date: daysAgo(200),
  },
  {
    id: 'demo_vendor_6',
    vendor_name: 'מכונאי אקספרס — גיל אברהם',
    contact_person: 'גיל אברהם',
    phone: '054-7006006',
    email: 'vendor6@natid-demo.com',
    service_type: ['mechanic', 'fuel_delivery'],
    vehicle_types_supported: ['private', 'motorcycle'],
    coverage_areas: ['center'],
    availability_status: 'offline',
    is_active: true,
    is_available_now: false,
    current_latitude: 32.0868,
    current_longitude: 34.8872,
    service_radius: 15,
    average_rating: 3.8,
    total_ratings: 10,
    average_response_time: 25,
    completion_rate: 0.8,
    total_calls_assigned: 35,
    works_24_7: false,
    working_hours_start: '08:00',
    working_hours_end: '20:00',
    payment_rate_per_call: 250,
    contract_status: 'active',
    is_location_sharing_enabled: false,
    notes: 'ספק חדש יחסית',
    created_date: daysAgo(60),
  },
  {
    id: 'demo_vendor_7',
    vendor_name: 'גרר הדרום — עומר דהן',
    contact_person: 'עומר דהן',
    phone: '054-7007007',
    email: 'vendor7@natid-demo.com',
    service_type: ['tow_truck'],
    vehicle_types_supported: ['private', 'commercial_light', 'truck', 'motorcycle'],
    coverage_areas: ['south'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 31.2518,
    current_longitude: 34.7913,
    service_radius: 50,
    average_rating: 4.3,
    total_ratings: 22,
    average_response_time: 18,
    completion_rate: 0.9,
    total_calls_assigned: 95,
    works_24_7: false,
    working_hours_start: '06:00',
    working_hours_end: '22:00',
    payment_rate_per_call: 450,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'מכסה את כל אזור הדרום כולל אילת',
    created_date: daysAgo(180),
  },
  {
    id: 'demo_vendor_8',
    vendor_name: 'שירותי דרך פלוס — ליאור שפירא',
    contact_person: 'ליאור שפירא',
    phone: '054-7008008',
    email: 'vendor8@natid-demo.com',
    service_type: ['multi_service'],
    vehicle_types_supported: ['private', 'commercial_light'],
    coverage_areas: ['center', 'sharon', 'lowlands'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 31.8928,
    current_longitude: 34.811,
    service_radius: 30,
    average_rating: 4.7,
    total_ratings: 55,
    average_response_time: 9,
    completion_rate: 0.96,
    total_calls_assigned: 280,
    works_24_7: true,
    working_hours_start: '00:00',
    working_hours_end: '23:59',
    payment_rate_per_call: 300,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'ספק מוביל — רב תחומי, ביצועים מצוינים',
    created_date: daysAgo(400),
  },
  {
    id: 'demo_vendor_9',
    vendor_name: 'גרר ירושלים — אורי גולדשטיין',
    contact_person: 'אורי גולדשטיין',
    phone: '054-7009009',
    email: 'vendor9@natid-demo.com',
    service_type: ['tow_truck', 'mechanic'],
    vehicle_types_supported: ['private', 'commercial_light'],
    coverage_areas: ['jerusalem'],
    availability_status: 'available',
    is_active: true,
    is_available_now: true,
    current_latitude: 31.7683,
    current_longitude: 35.2137,
    service_radius: 25,
    average_rating: 4.4,
    total_ratings: 30,
    average_response_time: 14,
    completion_rate: 0.91,
    total_calls_assigned: 110,
    works_24_7: false,
    working_hours_start: '06:00',
    working_hours_end: '23:00',
    payment_rate_per_call: 380,
    contract_status: 'active',
    is_location_sharing_enabled: true,
    notes: 'מכסה ירושלים והסביבה',
    created_date: daysAgo(280),
  },
  {
    id: 'demo_vendor_10',
    vendor_name: 'טכנו-גרר — תמר רוזנברג',
    contact_person: 'תמר רוזנברג',
    phone: '054-7010010',
    email: 'vendor10@natid-demo.com',
    service_type: ['tow_truck', 'tire_service', 'mechanic'],
    vehicle_types_supported: ['private', 'commercial_light', 'motorcycle'],
    coverage_areas: ['center', 'sharon'],
    availability_status: 'on_break',
    is_active: true,
    is_available_now: false,
    current_latitude: 32.1629,
    current_longitude: 34.8447,
    service_radius: 20,
    average_rating: 4.1,
    total_ratings: 12,
    average_response_time: 16,
    completion_rate: 0.87,
    total_calls_assigned: 50,
    works_24_7: false,
    working_hours_start: '07:00',
    working_hours_end: '21:00',
    payment_rate_per_call: 320,
    contract_status: 'pending',
    is_location_sharing_enabled: true,
    notes: 'ספקית חדשה, ביצועים טובים',
    created_date: daysAgo(45),
  },
];

// ===== CALLS =====
const calls = [
  // --- 10 COMPLETED calls ---
  {
    id: 'demo_call_1',
    call_number: 'C-2026020101',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'יוסי כהן',
    customer_phone: '054-3211234',
    customer_id: 'demo_customer_1',
    insurance_company: 'הראל',
    vehicle_plate: '12-345-67',
    vehicle_type: 'private',
    vehicle_model: 'טויוטה קורולה',
    issue_type: 'flat_tire',
    issue_description: 'פנצ\'ר בגלגל קדמי ימני',
    pickup_location_address: 'רחוב הרצל 45, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.0853,
    pickup_location_lon: 34.7818,
    assigned_vendor_id: 'demo_vendor_3',
    assigned_vendor_name: 'צמיגי השרון — אבי מזרחי',
    assigned_at: daysAgo(5),
    estimated_distance_km: 8,
    customer_source: 'phone',
    created_date: daysAgo(5),
    completed_date: daysAgo(5),
    closed_at: daysAgo(5),
    time_to_completion: 35,
    customer_rating: 5,
    customer_feedback: 'שירות מעולה, הגיע מהר',
    vendor_notes: 'הוחלף גלגל, לקוח המשיך בנסיעה',
    cost_to_vendor: 200,
    call_summary: 'קריאה C-2026020101: פנצ\'ר בגלגל קדמי. הספק צמיגי השרון הגיע וטיפל בהצלחה.',
    sla_response_deadline: daysAgo(5),
    sla_arrival_deadline: daysAgo(5),
  },
  {
    id: 'demo_call_2',
    call_number: 'C-2026020102',
    call_status: 'completed',
    call_priority: 'urgent',
    customer_name: 'שרה לוי',
    customer_phone: '052-9876543',
    customer_id: 'demo_customer_2',
    insurance_company: 'מגדל',
    vehicle_plate: '23-456-78',
    vehicle_type: 'private',
    vehicle_model: 'יונדאי i30',
    issue_type: 'stopped_driving',
    issue_description: 'רכב נעצר באמצע הדרך',
    pickup_location_address: 'שדרות רוטשילד 22, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.0636,
    pickup_location_lon: 34.7729,
    dropoff_location_address: 'מוסך מרכזי, רחוב הברזל 5, תל אביב',
    dropoff_location_city: 'תל אביב',
    dropoff_location_lat: 32.0977,
    dropoff_location_lon: 34.8017,
    assigned_vendor_id: 'demo_vendor_1',
    assigned_vendor_name: 'גרר המרכז — יוסי כהן',
    assigned_at: daysAgo(4),
    estimated_distance_km: 5,
    customer_source: 'phone',
    created_date: daysAgo(4),
    completed_date: daysAgo(4),
    closed_at: daysAgo(4),
    time_to_completion: 55,
    customer_rating: 4,
    customer_feedback: 'ספק מקצועי מאוד',
    vendor_notes: 'בוצעה גרירה למוסך',
    cost_to_vendor: 350,
    call_summary: 'קריאה C-2026020102: רכב נעצר. בוצעה גרירה למוסך ע"י גרר המרכז.',
    sla_response_deadline: daysAgo(4),
    sla_arrival_deadline: daysAgo(4),
  },
  {
    id: 'demo_call_3',
    call_number: 'C-2026020103',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'דוד מזרחי',
    customer_phone: '050-1112233',
    customer_id: 'demo_customer_3',
    insurance_company: 'כלל',
    vehicle_plate: '34-567-89',
    vehicle_type: 'private',
    vehicle_model: 'מאזדה 3',
    issue_type: 'dead_battery',
    issue_description: 'מצבר ריק',
    pickup_location_address: 'רחוב דיזנגוף 100, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.0789,
    pickup_location_lon: 34.7741,
    assigned_vendor_id: 'demo_vendor_2',
    assigned_vendor_name: 'מכונאי ניידות — דוד לוי',
    assigned_at: daysAgo(3),
    estimated_distance_km: 6,
    customer_source: 'phone',
    created_date: daysAgo(3),
    completed_date: daysAgo(3),
    closed_at: daysAgo(3),
    time_to_completion: 25,
    customer_rating: 5,
    customer_feedback: 'טיפול מהיר ויעיל',
    vendor_notes: 'הותקן מצבר חדש',
    cost_to_vendor: 280,
    call_summary: 'קריאה C-2026020103: מצבר ריק. הספק מכונאי ניידות הגיע והחליף מצבר.',
    sla_response_deadline: daysAgo(3),
    sla_arrival_deadline: daysAgo(3),
  },
  {
    id: 'demo_call_4',
    call_number: 'C-2026020104',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'רחל אברהם',
    customer_phone: '053-4445566',
    customer_id: 'demo_customer_4',
    insurance_company: 'הפניקס',
    vehicle_plate: '45-678-90',
    vehicle_type: 'private',
    vehicle_model: 'סקודה אוקטביה',
    issue_type: 'locked_keys',
    issue_description: 'מפתחות נעולים ברכב',
    pickup_location_address: 'רחוב ויצמן 15, כפר סבא',
    pickup_location_city: 'כפר סבא',
    pickup_location_lat: 32.1717,
    pickup_location_lon: 34.9069,
    assigned_vendor_id: 'demo_vendor_4',
    assigned_vendor_name: 'מנעולן 24/7 — רונן פרץ',
    assigned_at: daysAgo(3),
    estimated_distance_km: 12,
    customer_source: 'bot',
    created_date: daysAgo(3),
    completed_date: daysAgo(3),
    closed_at: daysAgo(3),
    time_to_completion: 40,
    customer_rating: 5,
    customer_feedback: 'מרוצה מהשירות',
    vendor_notes: 'נפתח הרכב ללא נזק',
    cost_to_vendor: 320,
    call_summary: 'קריאה C-2026020104: מפתחות נעולים. מנעולן 24/7 פתח את הרכב בהצלחה.',
    sla_response_deadline: daysAgo(3),
    sla_arrival_deadline: daysAgo(3),
  },
  {
    id: 'demo_call_5',
    call_number: 'C-2026020105',
    call_status: 'completed',
    call_priority: 'critical',
    customer_name: 'עומר שפירא',
    customer_phone: '054-7778899',
    customer_id: 'demo_customer_5',
    insurance_company: 'הראל',
    vehicle_plate: '56-789-01',
    vehicle_type: 'commercial_light',
    vehicle_model: 'פולקסווגן קאדי',
    issue_type: 'accident',
    issue_description: 'תאונה קלה — פח',
    pickup_location_address: 'דרך השלום 50, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.0588,
    pickup_location_lon: 34.7899,
    dropoff_location_address: 'מוסך אלדן, פתח תקווה',
    dropoff_location_city: 'פתח תקווה',
    dropoff_location_lat: 32.0868,
    dropoff_location_lon: 34.8872,
    assigned_vendor_id: 'demo_vendor_1',
    assigned_vendor_name: 'גרר המרכז — יוסי כהן',
    assigned_at: daysAgo(2),
    estimated_distance_km: 15,
    customer_source: 'phone',
    created_date: daysAgo(2),
    completed_date: daysAgo(2),
    closed_at: daysAgo(2),
    time_to_completion: 65,
    customer_rating: 4,
    customer_feedback: 'זמן המתנה סביר',
    vendor_notes: 'בוצעה גרירה למוסך, רכב נפגע בפנס קדמי',
    cost_to_vendor: 450,
    call_summary: 'קריאה C-2026020105: תאונה קלה. בוצעה גרירה למוסך אלדן.',
    sla_response_deadline: daysAgo(2),
    sla_arrival_deadline: daysAgo(2),
  },
  {
    id: 'demo_call_6',
    call_number: 'C-2026020106',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'מיכל דהן',
    customer_phone: '050-2223344',
    customer_id: 'demo_customer_6',
    insurance_company: 'מגדל',
    vehicle_plate: '67-890-12',
    vehicle_type: 'private',
    vehicle_model: 'הונדה סיוויק',
    issue_type: 'mechanical',
    issue_description: 'רעש חריג מהמנוע',
    pickup_location_address: 'רחוב סוקולוב 30, רמת גן',
    pickup_location_city: 'רמת גן',
    pickup_location_lat: 32.0686,
    pickup_location_lon: 34.8248,
    assigned_vendor_id: 'demo_vendor_2',
    assigned_vendor_name: 'מכונאי ניידות — דוד לוי',
    assigned_at: daysAgo(6),
    estimated_distance_km: 4,
    customer_source: 'phone',
    created_date: daysAgo(6),
    completed_date: daysAgo(6),
    closed_at: daysAgo(6),
    time_to_completion: 45,
    customer_rating: 5,
    customer_feedback: 'שירות מעולה ומקצועי',
    vendor_notes: 'תוקן חיבור רופף ברצועת מנוע',
    cost_to_vendor: 280,
    call_summary: 'קריאה C-2026020106: רעש חריג. מכונאי ניידות אבחן ותיקן.',
    sla_response_deadline: daysAgo(6),
    sla_arrival_deadline: daysAgo(6),
  },
  {
    id: 'demo_call_7',
    call_number: 'C-2026020107',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'גיל רוזנברג',
    customer_phone: '052-5556677',
    customer_id: 'demo_customer_7',
    vehicle_plate: '78-901-23',
    vehicle_type: 'private',
    vehicle_model: 'ניסאן קשקאי',
    issue_type: 'no_fuel',
    issue_description: 'נגמר הדלק',
    pickup_location_address: 'כביש 2 ליד מחלף נתניה',
    pickup_location_city: 'נתניה',
    pickup_location_lat: 32.3215,
    pickup_location_lon: 34.8532,
    assigned_vendor_id: 'demo_vendor_6',
    assigned_vendor_name: 'מכונאי אקספרס — גיל אברהם',
    assigned_at: daysAgo(7),
    estimated_distance_km: 10,
    customer_source: 'phone',
    created_date: daysAgo(7),
    completed_date: daysAgo(7),
    closed_at: daysAgo(7),
    time_to_completion: 30,
    customer_rating: 4,
    customer_feedback: 'הגיע בזמן',
    vendor_notes: 'תודלק 10 ליטר',
    cost_to_vendor: 250,
    call_summary: 'קריאה C-2026020107: נגמר הדלק. בוצע תידלוק במקום.',
    sla_response_deadline: daysAgo(7),
    sla_arrival_deadline: daysAgo(7),
  },
  {
    id: 'demo_call_8',
    call_number: 'C-2026020108',
    call_status: 'completed',
    call_priority: 'urgent',
    customer_name: 'נועה פרץ',
    customer_phone: '054-8889900',
    customer_id: 'demo_customer_1',
    insurance_company: 'הראל',
    vehicle_plate: '89-012-34',
    vehicle_type: 'private',
    vehicle_model: 'רנו קליאו',
    issue_type: 'stopped_driving',
    issue_description: 'רכב לא מתניע',
    pickup_location_address: 'רחוב הנשיא 8, ירושלים',
    pickup_location_city: 'ירושלים',
    pickup_location_lat: 31.7683,
    pickup_location_lon: 35.2137,
    dropoff_location_address: 'מוסך רנו ירושלים',
    dropoff_location_city: 'ירושלים',
    dropoff_location_lat: 31.7583,
    dropoff_location_lon: 35.2037,
    assigned_vendor_id: 'demo_vendor_9',
    assigned_vendor_name: 'גרר ירושלים — אורי גולדשטיין',
    assigned_at: daysAgo(8),
    estimated_distance_km: 7,
    customer_source: 'phone',
    created_date: daysAgo(8),
    completed_date: daysAgo(8),
    closed_at: daysAgo(8),
    time_to_completion: 50,
    customer_rating: 4,
    customer_feedback: 'ספק אמין',
    vendor_notes: 'בוצעה גרירה למוסך רנו',
    cost_to_vendor: 380,
    call_summary: 'קריאה C-2026020108: רכב לא מתניע. בוצעה גרירה למוסך.',
    sla_response_deadline: daysAgo(8),
    sla_arrival_deadline: daysAgo(8),
  },
  {
    id: 'demo_call_9',
    call_number: 'C-2026020109',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'תמר אזולאי',
    customer_phone: '050-1234000',
    customer_id: 'demo_customer_2',
    insurance_company: 'מגדל',
    vehicle_plate: '90-123-45',
    vehicle_type: 'private',
    vehicle_model: 'סיאט איביזה',
    issue_type: 'flat_tire',
    issue_description: 'שני פנצ\'רים',
    pickup_location_address: 'דרך בן גוריון 50, הרצליה',
    pickup_location_city: 'הרצליה',
    pickup_location_lat: 32.1629,
    pickup_location_lon: 34.8447,
    assigned_vendor_id: 'demo_vendor_3',
    assigned_vendor_name: 'צמיגי השרון — אבי מזרחי',
    assigned_at: daysAgo(10),
    estimated_distance_km: 14,
    customer_source: 'bot',
    created_date: daysAgo(10),
    completed_date: daysAgo(10),
    closed_at: daysAgo(10),
    time_to_completion: 60,
    customer_rating: 4,
    customer_feedback: 'עבודה מקצועית',
    vendor_notes: 'הוחלפו 2 צמיגים',
    cost_to_vendor: 400,
    call_summary: 'קריאה C-2026020109: שני פנצ\'רים. הוחלפו 2 צמיגים במקום.',
    sla_response_deadline: daysAgo(10),
    sla_arrival_deadline: daysAgo(10),
  },
  {
    id: 'demo_call_10',
    call_number: 'C-2026020110',
    call_status: 'completed',
    call_priority: 'normal',
    customer_name: 'אורי ביטון',
    customer_phone: '053-9998877',
    customer_id: 'demo_customer_3',
    insurance_company: 'כלל',
    vehicle_plate: '11-222-33',
    vehicle_type: 'private',
    vehicle_model: 'סוזוקי סוויפט',
    issue_type: 'mechanical',
    issue_description: 'חום יתר במנוע',
    pickup_location_address: 'רחוב אלנבי 60, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.067,
    pickup_location_lon: 34.769,
    assigned_vendor_id: 'demo_vendor_8',
    assigned_vendor_name: 'שירותי דרך פלוס — ליאור שפירא',
    assigned_at: daysAgo(12),
    estimated_distance_km: 9,
    customer_source: 'phone',
    created_date: daysAgo(12),
    completed_date: daysAgo(12),
    closed_at: daysAgo(12),
    time_to_completion: 40,
    customer_rating: 5,
    customer_feedback: 'מעולה!',
    vendor_notes: 'תוקנה דליפת נוזל קירור',
    cost_to_vendor: 300,
    call_summary: 'קריאה C-2026020110: חום יתר. תוקנה דליפת נוזל קירור במקום.',
    sla_response_deadline: daysAgo(12),
    sla_arrival_deadline: daysAgo(12),
  },
  // --- 3 IN_PROGRESS calls ---
  {
    id: 'demo_call_11',
    call_number: 'C-2026020111',
    call_status: 'in_progress',
    call_priority: 'urgent',
    customer_name: 'יעל גולדשטיין',
    customer_phone: '054-1119988',
    customer_id: 'demo_customer_4',
    insurance_company: 'הפניקס',
    vehicle_plate: '44-555-66',
    vehicle_type: 'private',
    vehicle_model: 'קיה ספורטאז\'',
    issue_type: 'mechanical',
    issue_description: 'מנוע לא מניע',
    pickup_location_address: 'רחוב ז\'בוטינסקי 40, פתח תקווה',
    pickup_location_city: 'פתח תקווה',
    pickup_location_lat: 32.0868,
    pickup_location_lon: 34.8872,
    assigned_vendor_id: 'demo_vendor_2',
    assigned_vendor_name: 'מכונאי ניידות — דוד לוי',
    assigned_at: hoursAgo(1),
    estimated_distance_km: 7,
    customer_source: 'phone',
    created_date: hoursAgo(2),
    internal_notes: 'לקוח VIP — טיפול מועדף',
    sla_response_deadline: hoursAgo(1),
    sla_arrival_deadline: minutesAgo(45),
  },
  {
    id: 'demo_call_12',
    call_number: 'C-2026020112',
    call_status: 'in_progress',
    call_priority: 'normal',
    customer_name: 'ליאור כהן',
    customer_phone: '050-3334455',
    customer_id: 'demo_customer_5',
    vehicle_plate: '77-888-99',
    vehicle_type: 'commercial_light',
    vehicle_model: 'פורד טרנזיט',
    issue_type: 'flat_tire',
    issue_description: 'פנצ\'ר בגלגל אחורי',
    pickup_location_address: 'אזור תעשייה, אשדוד',
    pickup_location_city: 'אשדוד',
    pickup_location_lat: 31.8044,
    pickup_location_lon: 34.6553,
    assigned_vendor_id: 'demo_vendor_8',
    assigned_vendor_name: 'שירותי דרך פלוס — ליאור שפירא',
    assigned_at: minutesAgo(45),
    estimated_distance_km: 12,
    customer_source: 'phone',
    created_date: hoursAgo(1),
    sla_response_deadline: minutesAgo(30),
    sla_arrival_deadline: minutesAgo(15),
  },
  {
    id: 'demo_call_13',
    call_number: 'C-2026020113',
    call_status: 'in_progress',
    call_priority: 'normal',
    customer_name: 'רונן דהן',
    customer_phone: '052-6667788',
    customer_id: 'demo_customer_8',
    vehicle_plate: '10-203-40',
    vehicle_type: 'private',
    vehicle_model: 'פולקסווגן גולף',
    issue_type: 'stuck_wheel',
    issue_description: 'בלם נתקע',
    pickup_location_address: 'שדרות ירושלים 12, רחובות',
    pickup_location_city: 'רחובות',
    pickup_location_lat: 31.8928,
    pickup_location_lon: 34.811,
    assigned_vendor_id: 'demo_vendor_2',
    assigned_vendor_name: 'מכונאי ניידות — דוד לוי',
    assigned_at: minutesAgo(30),
    estimated_distance_km: 5,
    customer_source: 'bot',
    created_date: hoursAgo(1),
    sla_response_deadline: minutesAgo(30),
    sla_arrival_deadline: minutesAgo(15),
  },
  // --- 3 VENDOR_ENROUTE calls ---
  {
    id: 'demo_call_14',
    call_number: 'C-2026020114',
    call_status: 'vendor_enroute',
    call_priority: 'urgent',
    customer_name: 'משה אגבריה',
    customer_phone: '054-2223344',
    customer_id: 'demo_customer_1',
    insurance_company: 'הראל',
    vehicle_plate: '50-607-80',
    vehicle_type: 'private',
    vehicle_model: 'שברולט ספארק',
    issue_type: 'dead_battery',
    issue_description: 'מצבר ישן',
    pickup_location_address: 'רחוב בגין 25, רמת גן',
    pickup_location_city: 'רמת גן',
    pickup_location_lat: 32.0686,
    pickup_location_lon: 34.8248,
    assigned_vendor_id: 'demo_vendor_8',
    assigned_vendor_name: 'שירותי דרך פלוס — ליאור שפירא',
    assigned_at: minutesAgo(15),
    estimated_distance_km: 10,
    estimated_arrival_time: minutesAgo(-10),
    customer_source: 'phone',
    created_date: minutesAgo(25),
    sla_response_deadline: minutesAgo(-5),
    sla_arrival_deadline: minutesAgo(-20),
  },
  {
    id: 'demo_call_15',
    call_number: 'C-2026020115',
    call_status: 'vendor_enroute',
    call_priority: 'normal',
    customer_name: 'אבי לוי',
    customer_phone: '050-4445566',
    customer_id: 'demo_customer_2',
    insurance_company: 'מגדל',
    vehicle_plate: '31-425-63',
    vehicle_type: 'private',
    vehicle_model: 'טויוטה קורולה',
    issue_type: 'mechanical',
    issue_description: 'דליפת שמן',
    pickup_location_address: 'רחוב הרצל 80, ראשון לציון',
    pickup_location_city: 'ראשון לציון',
    pickup_location_lat: 31.9635,
    pickup_location_lon: 34.8041,
    assigned_vendor_id: 'demo_vendor_2',
    assigned_vendor_name: 'מכונאי ניידות — דוד לוי',
    assigned_at: minutesAgo(10),
    estimated_distance_km: 6,
    estimated_arrival_time: minutesAgo(-15),
    customer_source: 'phone',
    created_date: minutesAgo(20),
    sla_response_deadline: minutesAgo(-10),
    sla_arrival_deadline: minutesAgo(-25),
  },
  {
    id: 'demo_call_16',
    call_number: 'C-2026020116',
    call_status: 'vendor_enroute',
    call_priority: 'critical',
    customer_name: 'דנה שפירא',
    customer_phone: '053-7778899',
    customer_id: 'demo_customer_3',
    insurance_company: 'כלל',
    vehicle_plate: '22-333-44',
    vehicle_type: 'private',
    vehicle_model: 'יונדאי i30',
    issue_type: 'accident',
    issue_description: 'תאונה עם נפגעים',
    pickup_location_address: 'כביש 4, ליד מחלף גהה',
    pickup_location_city: 'פתח תקווה',
    pickup_location_lat: 32.092,
    pickup_location_lon: 34.876,
    dropoff_location_address: 'בית חולים בילינסון',
    dropoff_location_city: 'פתח תקווה',
    dropoff_location_lat: 32.0868,
    dropoff_location_lon: 34.8872,
    assigned_vendor_id: 'demo_vendor_1',
    assigned_vendor_name: 'גרר המרכז — יוסי כהן',
    assigned_at: minutesAgo(8),
    estimated_distance_km: 3,
    estimated_arrival_time: minutesAgo(-5),
    customer_source: 'phone',
    created_date: minutesAgo(12),
    internal_notes: 'קריאה דחופה — תאונה עם נפגעים',
    sla_response_deadline: minutesAgo(-18),
    sla_arrival_deadline: minutesAgo(-33),
  },
  // --- 2 ASSIGNING calls ---
  {
    id: 'demo_call_17',
    call_number: 'C-2026020117',
    call_status: 'assigning',
    call_priority: 'urgent',
    customer_name: 'גל פרץ',
    customer_phone: '054-9990011',
    customer_id: 'demo_customer_4',
    insurance_company: 'הפניקס',
    vehicle_plate: '55-666-77',
    vehicle_type: 'private',
    vehicle_model: 'מאזדה 3',
    issue_type: 'locked_keys',
    issue_description: 'מפתח נשבר',
    pickup_location_address: 'רחוב ויצמן 42, כפר סבא',
    pickup_location_city: 'כפר סבא',
    pickup_location_lat: 32.1717,
    pickup_location_lon: 34.9069,
    assigned_vendor_id: 'demo_vendor_4',
    assigned_vendor_name: 'מנעולן 24/7 — רונן פרץ',
    assigned_at: minutesAgo(5),
    estimated_distance_km: 8,
    customer_source: 'phone',
    created_date: minutesAgo(10),
    sla_response_deadline: minutesAgo(-20),
    sla_arrival_deadline: minutesAgo(-35),
  },
  {
    id: 'demo_call_18',
    call_number: 'C-2026020118',
    call_status: 'assigning',
    call_priority: 'normal',
    customer_name: 'שירה כהן',
    customer_phone: '050-8887766',
    customer_id: 'demo_customer_6',
    vehicle_plate: '88-999-00',
    vehicle_type: 'commercial_light',
    vehicle_model: 'רנו קנגו',
    issue_type: 'stopped_driving',
    issue_description: 'תקלה חשמלית',
    pickup_location_address: 'דרך השלום 100, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.055,
    pickup_location_lon: 34.792,
    dropoff_location_address: 'מוסך רנו תל אביב',
    dropoff_location_city: 'תל אביב',
    dropoff_location_lat: 32.073,
    dropoff_location_lon: 34.788,
    assigned_vendor_id: 'demo_vendor_1',
    assigned_vendor_name: 'גרר המרכז — יוסי כהן',
    assigned_at: minutesAgo(3),
    estimated_distance_km: 5,
    customer_source: 'bot',
    created_date: minutesAgo(8),
    sla_response_deadline: minutesAgo(-22),
    sla_arrival_deadline: minutesAgo(-37),
  },
  // --- 5 AWAITING_ASSIGNMENT calls ---
  {
    id: 'demo_call_19',
    call_number: 'C-2026020119',
    call_status: 'awaiting_assignment',
    call_priority: 'normal',
    customer_name: 'יוני מזרחי',
    customer_phone: '052-1112233',
    customer_id: 'demo_customer_1',
    insurance_company: 'הראל',
    vehicle_plate: '33-444-55',
    vehicle_type: 'private',
    vehicle_model: 'סקודה אוקטביה',
    issue_type: 'flat_tire',
    issue_description: 'פנצ\'ר בגלגל קדמי',
    pickup_location_address: 'רחוב סוקולוב 5, נתניה',
    pickup_location_city: 'נתניה',
    pickup_location_lat: 32.3215,
    pickup_location_lon: 34.8532,
    customer_source: 'phone',
    created_date: minutesAgo(15),
    sla_response_deadline: minutesAgo(-15),
    sla_arrival_deadline: minutesAgo(-30),
  },
  {
    id: 'demo_call_20',
    call_number: 'C-2026020120',
    call_status: 'awaiting_assignment',
    call_priority: 'urgent',
    customer_name: 'אלון ביטון',
    customer_phone: '054-3332211',
    customer_id: 'demo_customer_5',
    vehicle_plate: '66-777-88',
    vehicle_type: 'private',
    vehicle_model: 'הונדה סיוויק',
    issue_type: 'dead_battery',
    issue_description: 'בעיה בטעינת מצבר',
    pickup_location_address: 'שדרות ירושלים 25, מודיעין',
    pickup_location_city: 'מודיעין',
    pickup_location_lat: 31.8969,
    pickup_location_lon: 35.0101,
    customer_source: 'phone',
    created_date: minutesAgo(20),
    sla_response_deadline: minutesAgo(-10),
    sla_arrival_deadline: minutesAgo(-25),
  },
  {
    id: 'demo_call_21',
    call_number: 'C-2026020121',
    call_status: 'awaiting_assignment',
    call_priority: 'normal',
    customer_name: 'נעמי אזולאי',
    customer_phone: '050-5554433',
    customer_id: 'demo_customer_2',
    insurance_company: 'מגדל',
    vehicle_plate: '99-000-11',
    vehicle_type: 'private',
    vehicle_model: 'סוזוקי סוויפט',
    issue_type: 'no_fuel',
    issue_description: 'נגמר הדלק',
    pickup_location_address: 'כביש 6, ליד מחלף אלוף שדה',
    pickup_location_city: 'ראשון לציון',
    pickup_location_lat: 31.97,
    pickup_location_lon: 34.82,
    customer_source: 'phone',
    created_date: minutesAgo(25),
    sla_response_deadline: minutesAgo(-5),
    sla_arrival_deadline: minutesAgo(-20),
  },
  {
    id: 'demo_call_22',
    call_number: 'C-2026020122',
    call_status: 'awaiting_assignment',
    call_priority: 'normal',
    customer_name: 'עדי רוזנברג',
    customer_phone: '053-6665544',
    customer_id: 'demo_customer_7',
    vehicle_plate: '12-111-22',
    vehicle_type: 'private',
    vehicle_model: 'ניסאן קשקאי',
    issue_type: 'mechanical',
    issue_description: 'חום יתר במנוע',
    pickup_location_address: 'דרך העצמאות 15, חיפה',
    pickup_location_city: 'חיפה',
    pickup_location_lat: 32.794,
    pickup_location_lon: 34.9896,
    customer_source: 'bot',
    created_date: minutesAgo(30),
    sla_response_deadline: minutesAgo(0),
    sla_arrival_deadline: minutesAgo(-15),
  },
  {
    id: 'demo_call_23',
    call_number: 'C-2026020123',
    call_status: 'awaiting_assignment',
    call_priority: 'critical',
    customer_name: 'משה גולדשטיין',
    customer_phone: '054-7776655',
    customer_id: 'demo_customer_3',
    insurance_company: 'כלל',
    vehicle_plate: '33-222-11',
    vehicle_type: 'private',
    vehicle_model: 'יונדאי i30',
    issue_type: 'accident',
    issue_description: 'פגע וברח',
    pickup_location_address: 'רחוב אלנבי 30, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.066,
    pickup_location_lon: 34.769,
    dropoff_location_address: 'מוסך מרכזי תל אביב',
    dropoff_location_city: 'תל אביב',
    dropoff_location_lat: 32.097,
    dropoff_location_lon: 34.801,
    customer_source: 'phone',
    created_date: minutesAgo(5),
    internal_notes: 'דחוף — פגע וברח, יש צורך בתיעוד',
    sla_response_deadline: minutesAgo(-25),
    sla_arrival_deadline: minutesAgo(-40),
  },
  // --- 5 WAITING_TREATMENT calls ---
  {
    id: 'demo_call_24',
    call_number: 'C-2026020124',
    call_status: 'waiting_treatment',
    call_priority: 'normal',
    customer_name: 'חנה לוי',
    customer_phone: '050-9998877',
    customer_id: 'demo_customer_8',
    vehicle_plate: '44-333-22',
    vehicle_type: 'private',
    vehicle_model: 'טויוטה קורולה',
    issue_type: 'locked_keys',
    issue_description: 'איבוד מפתח',
    pickup_location_address: 'רחוב הרצל 30, ראשון לציון',
    pickup_location_city: 'ראשון לציון',
    pickup_location_lat: 31.963,
    pickup_location_lon: 34.804,
    customer_source: 'phone',
    created_date: minutesAgo(3),
    sla_response_deadline: minutesAgo(-27),
    sla_arrival_deadline: minutesAgo(-42),
  },
  {
    id: 'demo_call_25',
    call_number: 'C-2026020125',
    call_status: 'waiting_treatment',
    call_priority: 'normal',
    customer_name: 'עמית פרץ',
    customer_phone: '054-2221100',
    customer_id: 'demo_customer_4',
    insurance_company: 'הפניקס',
    vehicle_plate: '55-444-33',
    vehicle_type: 'motorcycle',
    vehicle_model: 'ימאהה MT-07',
    issue_type: 'mechanical',
    issue_description: 'בעיה בגיר',
    pickup_location_address: 'רחוב דיזנגוף 200, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.084,
    pickup_location_lon: 34.774,
    customer_source: 'phone',
    created_date: minutesAgo(2),
    sla_response_deadline: minutesAgo(-28),
    sla_arrival_deadline: minutesAgo(-43),
  },
  {
    id: 'demo_call_26',
    call_number: 'C-2026020126',
    call_status: 'waiting_treatment',
    call_priority: 'urgent',
    customer_name: 'איתן שפירא',
    customer_phone: '052-8887766',
    customer_id: 'demo_customer_6',
    vehicle_plate: '66-555-44',
    vehicle_type: 'commercial_light',
    vehicle_model: 'מרצדס ספרינטר',
    issue_type: 'stopped_driving',
    issue_description: 'רכב נעצר באמצע הדרך',
    pickup_location_address: 'כביש 1, ליד מחלף לטרון',
    pickup_location_city: 'מודיעין',
    pickup_location_lat: 31.84,
    pickup_location_lon: 34.98,
    dropoff_location_address: 'מוסך מרצדס מודיעין',
    dropoff_location_city: 'מודיעין',
    dropoff_location_lat: 31.897,
    dropoff_location_lon: 35.01,
    customer_source: 'phone',
    created_date: minutesAgo(1),
    sla_response_deadline: minutesAgo(-29),
    sla_arrival_deadline: minutesAgo(-44),
  },
  {
    id: 'demo_call_27',
    call_number: 'C-2026020127',
    call_status: 'waiting_treatment',
    call_priority: 'normal',
    customer_name: 'שלמה כהן',
    customer_phone: '050-1110099',
    customer_id: 'demo_customer_1',
    insurance_company: 'הראל',
    vehicle_plate: '77-666-55',
    vehicle_type: 'private',
    vehicle_model: 'קיה ספורטאז\'',
    issue_type: 'flat_tire',
    issue_description: 'פנצ\'ר בגלגל אחורי',
    pickup_location_address: 'רחוב הנשיא 20, באר שבע',
    pickup_location_city: 'באר שבע',
    pickup_location_lat: 31.2518,
    pickup_location_lon: 34.7913,
    customer_source: 'bot',
    created_date: minutesAgo(1),
    sla_response_deadline: minutesAgo(-29),
    sla_arrival_deadline: minutesAgo(-44),
  },
  {
    id: 'demo_call_28',
    call_number: 'C-2026020128',
    call_status: 'waiting_treatment',
    call_priority: 'normal',
    customer_name: 'מוריה דהן',
    customer_phone: '054-3334455',
    customer_id: 'demo_customer_2',
    insurance_company: 'מגדל',
    vehicle_plate: '88-777-66',
    vehicle_type: 'private',
    vehicle_model: 'רנו קליאו',
    issue_type: 'other',
    issue_description: 'בעיה בבלמים',
    pickup_location_address: 'רחוב סוקולוב 40, הרצליה',
    pickup_location_city: 'הרצליה',
    pickup_location_lat: 32.162,
    pickup_location_lon: 34.844,
    customer_source: 'phone',
    created_date: minutesAgo(0),
    sla_response_deadline: minutesAgo(-30),
    sla_arrival_deadline: minutesAgo(-45),
  },
  // --- 2 CANCELLED calls ---
  {
    id: 'demo_call_29',
    call_number: 'C-2026020129',
    call_status: 'cancelled',
    call_priority: 'normal',
    customer_name: 'רוני אברהם',
    customer_phone: '050-6665544',
    customer_id: 'demo_customer_8',
    vehicle_plate: '99-888-77',
    vehicle_type: 'private',
    vehicle_model: 'הונדה סיוויק',
    issue_type: 'dead_battery',
    issue_description: 'מצבר ריק',
    pickup_location_address: 'רחוב הרצל 55, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.08,
    pickup_location_lon: 34.78,
    customer_source: 'phone',
    created_date: daysAgo(1),
    internal_notes: 'לקוח ביטל — הצליח להניע בעצמו',
    sla_response_deadline: daysAgo(1),
    sla_arrival_deadline: daysAgo(1),
  },
  {
    id: 'demo_call_30',
    call_number: 'C-2026020130',
    call_status: 'cancelled',
    call_priority: 'normal',
    customer_name: 'דינה מזרחי',
    customer_phone: '053-4443322',
    customer_id: 'demo_customer_3',
    insurance_company: 'כלל',
    vehicle_plate: '11-000-99',
    vehicle_type: 'private',
    vehicle_model: 'סיאט איביזה',
    issue_type: 'no_fuel',
    issue_description: 'נגמר הדלק',
    pickup_location_address: 'רחוב אלנבי 20, תל אביב',
    pickup_location_city: 'תל אביב',
    pickup_location_lat: 32.065,
    pickup_location_lon: 34.768,
    customer_source: 'bot',
    created_date: daysAgo(2),
    internal_notes: 'לקוחה מצאה תחנת דלק בקרבת מקום',
    sla_response_deadline: daysAgo(2),
    sla_arrival_deadline: daysAgo(2),
  },
];

// ===== WORK QUEUE =====
const workQueue = [
  { id: 'demo_queue_1', call_id: 'demo_call_24', queue_status: 'waiting', priority_score: 70, waiting_since: minutesAgo(3), created_date: minutesAgo(3) },
  { id: 'demo_queue_2', call_id: 'demo_call_25', queue_status: 'waiting', priority_score: 65, waiting_since: minutesAgo(2), created_date: minutesAgo(2) },
  { id: 'demo_queue_3', call_id: 'demo_call_26', queue_status: 'waiting', priority_score: 90, waiting_since: minutesAgo(1), created_date: minutesAgo(1) },
  { id: 'demo_queue_4', call_id: 'demo_call_27', queue_status: 'waiting', priority_score: 60, waiting_since: minutesAgo(1), created_date: minutesAgo(1) },
  { id: 'demo_queue_5', call_id: 'demo_call_28', queue_status: 'waiting', priority_score: 55, waiting_since: minutesAgo(0), created_date: minutesAgo(0) },
  { id: 'demo_queue_6', call_id: 'demo_call_19', queue_status: 'waiting', priority_score: 68, waiting_since: minutesAgo(15), created_date: minutesAgo(15) },
  { id: 'demo_queue_7', call_id: 'demo_call_20', queue_status: 'waiting', priority_score: 85, waiting_since: minutesAgo(20), created_date: minutesAgo(20) },
  { id: 'demo_queue_8', call_id: 'demo_call_21', queue_status: 'assigned_to_agent', assigned_to_agent: 'operator1@natid-demo.com', priority_score: 62, waiting_since: minutesAgo(25), assigned_at: minutesAgo(10), created_date: minutesAgo(25) },
  { id: 'demo_queue_9', call_id: 'demo_call_22', queue_status: 'assigned_to_agent', assigned_to_agent: 'operator2@natid-demo.com', priority_score: 58, waiting_since: minutesAgo(30), assigned_at: minutesAgo(5), created_date: minutesAgo(30) },
  { id: 'demo_queue_10', call_id: 'demo_call_23', queue_status: 'waiting', priority_score: 95, waiting_since: minutesAgo(5), created_date: minutesAgo(5) },
];

// ===== CALL HISTORY =====
const callHistory = [
  { id: 'demo_history_1', call_id: 'demo_call_1', call_number: 'C-2026020101', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה נוצרה', changed_by: 'מערכת', created_date: daysAgo(5) },
  { id: 'demo_history_2', call_id: 'demo_call_1', call_number: 'C-2026020101', change_type: 'vendor_assignment', new_value: 'צמיגי השרון — אבי מזרחי', notes: 'ספק שובץ לקריאה', changed_by: 'operator1@natid-demo.com', created_date: daysAgo(5) },
  { id: 'demo_history_3', call_id: 'demo_call_1', call_number: 'C-2026020101', change_type: 'status_change', new_value: 'completed', notes: 'קריאה הושלמה — חתימת לקוח התקבלה', changed_by: 'צמיגי השרון — אבי מזרחי', created_date: daysAgo(5) },
  { id: 'demo_history_4', call_id: 'demo_call_2', call_number: 'C-2026020102', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה נוצרה', changed_by: 'מערכת', created_date: daysAgo(4) },
  { id: 'demo_history_5', call_id: 'demo_call_2', call_number: 'C-2026020102', change_type: 'vendor_assignment', new_value: 'גרר המרכז — יוסי כהן', notes: 'ספק שובץ לקריאה', changed_by: 'operator1@natid-demo.com', created_date: daysAgo(4) },
  { id: 'demo_history_6', call_id: 'demo_call_2', call_number: 'C-2026020102', change_type: 'status_change', new_value: 'in_progress', notes: 'ספק הגיע למיקום', changed_by: 'גרר המרכז — יוסי כהן', created_date: daysAgo(4) },
  { id: 'demo_history_7', call_id: 'demo_call_2', call_number: 'C-2026020102', change_type: 'status_change', new_value: 'completed', notes: 'קריאה הושלמה', changed_by: 'גרר המרכז — יוסי כהן', created_date: daysAgo(4) },
  { id: 'demo_history_8', call_id: 'demo_call_5', call_number: 'C-2026020105', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה דחופה — תאונה', changed_by: 'מערכת', created_date: daysAgo(2) },
  { id: 'demo_history_9', call_id: 'demo_call_5', call_number: 'C-2026020105', change_type: 'vendor_assignment', new_value: 'גרר המרכז — יוסי כהן', notes: 'שובץ ספק דחוף', changed_by: 'operator2@natid-demo.com', created_date: daysAgo(2) },
  { id: 'demo_history_10', call_id: 'demo_call_5', call_number: 'C-2026020105', change_type: 'status_change', new_value: 'completed', notes: 'גרירה הושלמה', changed_by: 'גרר המרכז — יוסי כהן', created_date: daysAgo(2) },
  { id: 'demo_history_11', call_id: 'demo_call_11', call_number: 'C-2026020111', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה נוצרה', changed_by: 'מערכת', created_date: hoursAgo(2) },
  { id: 'demo_history_12', call_id: 'demo_call_11', call_number: 'C-2026020111', change_type: 'vendor_assignment', new_value: 'מכונאי ניידות — דוד לוי', notes: 'ספק שובץ', changed_by: 'operator1@natid-demo.com', created_date: hoursAgo(1) },
  { id: 'demo_history_13', call_id: 'demo_call_11', call_number: 'C-2026020111', change_type: 'status_change', new_value: 'in_progress', notes: 'ספק הגיע, מתחיל טיפול', changed_by: 'מכונאי ניידות — דוד לוי', created_date: minutesAgo(30) },
  { id: 'demo_history_14', call_id: 'demo_call_14', call_number: 'C-2026020114', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה נוצרה', changed_by: 'מערכת', created_date: minutesAgo(25) },
  { id: 'demo_history_15', call_id: 'demo_call_14', call_number: 'C-2026020114', change_type: 'vendor_assignment', new_value: 'שירותי דרך פלוס — ליאור שפירא', notes: 'ספק שובץ', changed_by: 'operator1@natid-demo.com', created_date: minutesAgo(15) },
  { id: 'demo_history_16', call_id: 'demo_call_16', call_number: 'C-2026020116', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה דחופה — תאונה', changed_by: 'מערכת', created_date: minutesAgo(12) },
  { id: 'demo_history_17', call_id: 'demo_call_16', call_number: 'C-2026020116', change_type: 'vendor_assignment', new_value: 'גרר המרכז — יוסי כהן', notes: 'שובץ ספק דחוף', changed_by: 'מערכת', created_date: minutesAgo(8) },
  { id: 'demo_history_18', call_id: 'demo_call_29', call_number: 'C-2026020129', change_type: 'status_change', new_value: 'cancelled', notes: 'לקוח ביטל — הצליח להניע בעצמו', changed_by: 'operator2@natid-demo.com', created_date: daysAgo(1) },
  { id: 'demo_history_19', call_id: 'demo_call_30', call_number: 'C-2026020130', change_type: 'status_change', new_value: 'cancelled', notes: 'לקוחה מצאה תחנת דלק', changed_by: 'operator1@natid-demo.com', created_date: daysAgo(2) },
  { id: 'demo_history_20', call_id: 'demo_call_24', call_number: 'C-2026020124', change_type: 'status_change', new_value: 'waiting_treatment', notes: 'קריאה חדשה', changed_by: 'מערכת', created_date: minutesAgo(3) },
];

// ===== VENDOR RATINGS =====
const vendorRatings = [
  { id: 'demo_rating_1', vendor_id: 'demo_vendor_1', vendor_name: 'גרר המרכז — יוסי כהן', call_id: 'demo_call_2', call_number: 'C-2026020102', overall_rating: 4, response_time_rating: 4, service_quality_rating: 5, professionalism_rating: 4, communication_rating: 4, feedback: 'שירות מעולה ומקצועי', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(4) },
  { id: 'demo_rating_2', vendor_id: 'demo_vendor_3', vendor_name: 'צמיגי השרון — אבי מזרחי', call_id: 'demo_call_1', call_number: 'C-2026020101', overall_rating: 5, response_time_rating: 5, service_quality_rating: 5, professionalism_rating: 5, communication_rating: 5, feedback: 'הגיע מהר, עבודה יעילה', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(5) },
  { id: 'demo_rating_3', vendor_id: 'demo_vendor_2', vendor_name: 'מכונאי ניידות — דוד לוי', call_id: 'demo_call_3', call_number: 'C-2026020103', overall_rating: 5, response_time_rating: 5, service_quality_rating: 5, professionalism_rating: 5, communication_rating: 4, feedback: 'מקצועי ואמין', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(3) },
  { id: 'demo_rating_4', vendor_id: 'demo_vendor_4', vendor_name: 'מנעולן 24/7 — רונן פרץ', call_id: 'demo_call_4', call_number: 'C-2026020104', overall_rating: 5, response_time_rating: 4, service_quality_rating: 5, professionalism_rating: 5, communication_rating: 5, feedback: 'מרוצה מאוד מהשירות', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(3) },
  { id: 'demo_rating_5', vendor_id: 'demo_vendor_1', vendor_name: 'גרר המרכז — יוסי כהן', call_id: 'demo_call_5', call_number: 'C-2026020105', overall_rating: 4, response_time_rating: 3, service_quality_rating: 4, professionalism_rating: 4, communication_rating: 4, feedback: 'זמן המתנה סביר', completed_on_time: false, would_recommend: true, rating_source: 'customer', created_date: daysAgo(2) },
  { id: 'demo_rating_6', vendor_id: 'demo_vendor_2', vendor_name: 'מכונאי ניידות — דוד לוי', call_id: 'demo_call_6', call_number: 'C-2026020106', overall_rating: 5, response_time_rating: 5, service_quality_rating: 5, professionalism_rating: 5, communication_rating: 5, feedback: 'שירות מעולה ומקצועי', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(6) },
  { id: 'demo_rating_7', vendor_id: 'demo_vendor_6', vendor_name: 'מכונאי אקספרס — גיל אברהם', call_id: 'demo_call_7', call_number: 'C-2026020107', overall_rating: 4, response_time_rating: 4, service_quality_rating: 4, professionalism_rating: 3, communication_rating: 4, feedback: 'טיפול סביר', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(7) },
  { id: 'demo_rating_8', vendor_id: 'demo_vendor_9', vendor_name: 'גרר ירושלים — אורי גולדשטיין', call_id: 'demo_call_8', call_number: 'C-2026020108', overall_rating: 4, response_time_rating: 4, service_quality_rating: 4, professionalism_rating: 4, communication_rating: 4, feedback: 'ספק אמין', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(8) },
  { id: 'demo_rating_9', vendor_id: 'demo_vendor_3', vendor_name: 'צמיגי השרון — אבי מזרחי', call_id: 'demo_call_9', call_number: 'C-2026020109', overall_rating: 4, response_time_rating: 3, service_quality_rating: 5, professionalism_rating: 4, communication_rating: 4, feedback: 'עבודה מקצועית', completed_on_time: true, would_recommend: true, rating_source: 'admin', created_date: daysAgo(10) },
  { id: 'demo_rating_10', vendor_id: 'demo_vendor_8', vendor_name: 'שירותי דרך פלוס — ליאור שפירא', call_id: 'demo_call_10', call_number: 'C-2026020110', overall_rating: 5, response_time_rating: 5, service_quality_rating: 5, professionalism_rating: 5, communication_rating: 5, feedback: 'מעולה!', completed_on_time: true, would_recommend: true, rating_source: 'customer', created_date: daysAgo(12) },
];

// ===== VENDOR PAYMENTS =====
const vendorPayments = [
  { id: 'demo_payment_1', vendor_id: 'demo_vendor_3', call_id: 'demo_call_1', amount: 200, payment_status: 'paid', created_date: daysAgo(4) },
  { id: 'demo_payment_2', vendor_id: 'demo_vendor_1', call_id: 'demo_call_2', amount: 350, payment_status: 'paid', created_date: daysAgo(3) },
  { id: 'demo_payment_3', vendor_id: 'demo_vendor_2', call_id: 'demo_call_3', amount: 280, payment_status: 'paid', created_date: daysAgo(2) },
  { id: 'demo_payment_4', vendor_id: 'demo_vendor_4', call_id: 'demo_call_4', amount: 320, payment_status: 'paid', created_date: daysAgo(2) },
  { id: 'demo_payment_5', vendor_id: 'demo_vendor_1', call_id: 'demo_call_5', amount: 450, payment_status: 'pending', created_date: daysAgo(1) },
  { id: 'demo_payment_6', vendor_id: 'demo_vendor_2', call_id: 'demo_call_6', amount: 280, payment_status: 'paid', created_date: daysAgo(5) },
  { id: 'demo_payment_7', vendor_id: 'demo_vendor_6', call_id: 'demo_call_7', amount: 250, payment_status: 'paid', created_date: daysAgo(6) },
  { id: 'demo_payment_8', vendor_id: 'demo_vendor_9', call_id: 'demo_call_8', amount: 380, payment_status: 'pending', created_date: daysAgo(7) },
  { id: 'demo_payment_9', vendor_id: 'demo_vendor_3', call_id: 'demo_call_9', amount: 400, payment_status: 'paid', created_date: daysAgo(9) },
  { id: 'demo_payment_10', vendor_id: 'demo_vendor_8', call_id: 'demo_call_10', amount: 300, payment_status: 'paid', created_date: daysAgo(11) },
];

// ===== VENDOR CONTRACTS =====
const vendorContracts = [
  { id: 'demo_contract_1', vendor_id: 'demo_vendor_1', vendor_name: 'גרר המרכז — יוסי כהן', contract_number: 'CON-2026-1001', contract_type: 'yearly', status: 'active', start_date: daysAgo(180), end_date: daysFromNow(185), terms: 'תנאי חוזה סטנדרטיים — שירותי גרירה', expiry_reminder_sent: false, created_date: daysAgo(180) },
  { id: 'demo_contract_2', vendor_id: 'demo_vendor_2', vendor_name: 'מכונאי ניידות — דוד לוי', contract_number: 'CON-2026-1002', contract_type: 'yearly', status: 'active', start_date: daysAgo(200), end_date: daysFromNow(165), terms: 'תנאי חוזה סטנדרטיים — שירותי מכונאות', expiry_reminder_sent: false, created_date: daysAgo(200) },
  { id: 'demo_contract_3', vendor_id: 'demo_vendor_3', vendor_name: 'צמיגי השרון — אבי מזרחי', contract_number: 'CON-2026-1003', contract_type: 'monthly', status: 'active', start_date: daysAgo(30), end_date: daysFromNow(0), terms: 'חוזה חודשי — שירותי צמיגים', expiry_reminder_sent: true, created_date: daysAgo(30) },
  { id: 'demo_contract_4', vendor_id: 'demo_vendor_4', vendor_name: 'מנעולן 24/7 — רונן פרץ', contract_number: 'CON-2026-1004', contract_type: 'yearly', status: 'active', start_date: daysAgo(150), end_date: daysFromNow(215), terms: 'תנאי חוזה סטנדרטיים — שירותי מנעולנות', expiry_reminder_sent: false, created_date: daysAgo(150) },
  { id: 'demo_contract_5', vendor_id: 'demo_vendor_5', vendor_name: 'גרר הצפון — משה ביטון', contract_number: 'CON-2026-1005', contract_type: 'yearly', status: 'active', start_date: daysAgo(120), end_date: daysFromNow(245), terms: 'תנאי חוזה סטנדרטיים — שירותי גרירה צפון', expiry_reminder_sent: false, created_date: daysAgo(120) },
  { id: 'demo_contract_6', vendor_id: 'demo_vendor_6', vendor_name: 'מכונאי אקספרס — גיל אברהם', contract_number: 'CON-2026-1006', contract_type: 'per_call', status: 'active', start_date: daysAgo(60), end_date: daysFromNow(305), terms: 'תשלום לפי קריאה', expiry_reminder_sent: false, created_date: daysAgo(60) },
  { id: 'demo_contract_7', vendor_id: 'demo_vendor_7', vendor_name: 'גרר הדרום — עומר דהן', contract_number: 'CON-2026-1007', contract_type: 'yearly', status: 'active', start_date: daysAgo(90), end_date: daysFromNow(275), terms: 'תנאי חוזה סטנדרטיים — שירותי גרירה דרום', expiry_reminder_sent: false, created_date: daysAgo(90) },
  { id: 'demo_contract_8', vendor_id: 'demo_vendor_8', vendor_name: 'שירותי דרך פלוס — ליאור שפירא', contract_number: 'CON-2026-1008', contract_type: 'yearly', status: 'active', start_date: daysAgo(300), end_date: daysFromNow(65), terms: 'חוזה רב-תחומי — כולל כל השירותים', expiry_reminder_sent: false, created_date: daysAgo(300) },
  { id: 'demo_contract_9', vendor_id: 'demo_vendor_9', vendor_name: 'גרר ירושלים — אורי גולדשטיין', contract_number: 'CON-2026-1009', contract_type: 'yearly', status: 'active', start_date: daysAgo(250), end_date: daysFromNow(115), terms: 'תנאי חוזה סטנדרטיים — שירותי גרירה ירושלים', expiry_reminder_sent: false, created_date: daysAgo(250) },
  { id: 'demo_contract_10', vendor_id: 'demo_vendor_10', vendor_name: 'טכנו-גרר — תמר רוזנברג', contract_number: 'CON-2026-1010', contract_type: 'monthly', status: 'pending', start_date: daysAgo(15), end_date: daysFromNow(15), terms: 'חוזה זמני — תקופת ניסיון', expiry_reminder_sent: false, created_date: daysAgo(15) },
];

// ===== VENDOR LOCATIONS =====
const vendorLocations = [
  { id: 'demo_loc_1', vendor_id: 'demo_vendor_1', vendor_name: 'גרר המרכז — יוסי כהן', latitude: 32.0853, longitude: 34.7818, accuracy: 10, speed: 0, heading: 0, battery_level: 85, is_available: true, is_tracking_active: true, created_date: minutesAgo(5) },
  { id: 'demo_loc_2', vendor_id: 'demo_vendor_1', vendor_name: 'גרר המרכז — יוסי כהן', latitude: 32.088, longitude: 34.785, accuracy: 15, speed: 45, heading: 90, battery_level: 84, is_available: true, is_tracking_active: true, created_date: minutesAgo(10) },
  { id: 'demo_loc_3', vendor_id: 'demo_vendor_2', vendor_name: 'מכונאי ניידות — דוד לוי', latitude: 31.9635, longitude: 34.8041, accuracy: 8, speed: 0, heading: 0, battery_level: 72, is_available: true, is_tracking_active: true, created_date: minutesAgo(3) },
  { id: 'demo_loc_4', vendor_id: 'demo_vendor_2', vendor_name: 'מכונאי ניידות — דוד לוי', latitude: 31.965, longitude: 34.806, accuracy: 12, speed: 30, heading: 180, battery_level: 71, is_available: true, is_tracking_active: true, created_date: minutesAgo(8) },
  { id: 'demo_loc_5', vendor_id: 'demo_vendor_3', vendor_name: 'צמיגי השרון — אבי מזרחי', latitude: 32.3215, longitude: 34.8532, accuracy: 10, speed: 0, heading: 0, battery_level: 90, is_available: true, is_tracking_active: true, created_date: minutesAgo(2) },
  { id: 'demo_loc_6', vendor_id: 'demo_vendor_4', vendor_name: 'מנעולן 24/7 — רונן פרץ', latitude: 32.0686, longitude: 34.8248, accuracy: 10, speed: 55, heading: 270, battery_level: 60, is_available: false, is_tracking_active: true, created_date: minutesAgo(1) },
  { id: 'demo_loc_7', vendor_id: 'demo_vendor_5', vendor_name: 'גרר הצפון — משה ביטון', latitude: 32.794, longitude: 34.9896, accuracy: 20, speed: 0, heading: 0, battery_level: 95, is_available: true, is_tracking_active: true, created_date: minutesAgo(7) },
  { id: 'demo_loc_8', vendor_id: 'demo_vendor_7', vendor_name: 'גרר הדרום — עומר דהן', latitude: 31.2518, longitude: 34.7913, accuracy: 15, speed: 0, heading: 0, battery_level: 78, is_available: true, is_tracking_active: true, created_date: minutesAgo(4) },
  { id: 'demo_loc_9', vendor_id: 'demo_vendor_8', vendor_name: 'שירותי דרך פלוס — ליאור שפירא', latitude: 31.8928, longitude: 34.811, accuracy: 8, speed: 40, heading: 45, battery_level: 65, is_available: true, is_tracking_active: true, created_date: minutesAgo(2) },
  { id: 'demo_loc_10', vendor_id: 'demo_vendor_9', vendor_name: 'גרר ירושלים — אורי גולדשטיין', latitude: 31.7683, longitude: 35.2137, accuracy: 12, speed: 0, heading: 0, battery_level: 88, is_available: true, is_tracking_active: true, created_date: minutesAgo(6) },
  { id: 'demo_loc_11', vendor_id: 'demo_vendor_10', vendor_name: 'טכנו-גרר — תמר רוזנברג', latitude: 32.1629, longitude: 34.8447, accuracy: 10, speed: 0, heading: 0, battery_level: 45, is_available: false, is_tracking_active: true, created_date: minutesAgo(15) },
  { id: 'demo_loc_12', vendor_id: 'demo_vendor_6', vendor_name: 'מכונאי אקספרס — גיל אברהם', latitude: 32.0868, longitude: 34.8872, accuracy: 25, speed: 0, heading: 0, battery_level: 30, is_available: false, is_tracking_active: false, created_date: hoursAgo(2) },
];

// ===== NOTIFICATIONS =====
const notifications = [
  { id: 'demo_notif_1', user_id: 'demo_user_admin', title: 'קריאה חדשה התקבלה', message: 'קריאה C-2026020124 נכנסה למערכת — ממתינה לטיפול', type: 'info', related_entity_type: 'call', is_read: false, link: '/Calls', created_date: minutesAgo(3) },
  { id: 'demo_notif_2', user_id: 'demo_user_admin', title: 'ספק שובץ לקריאה', message: 'גרר המרכז שובץ לקריאה C-2026020116', type: 'success', related_entity_type: 'call', is_read: false, link: '/Calls', created_date: minutesAgo(8) },
  { id: 'demo_notif_3', user_id: 'demo_user_admin', title: 'אזהרת SLA', message: 'קריאה C-2026020120 קרובה לחריגת SLA — 10 דקות נותרו', type: 'warning', related_entity_type: 'call', is_read: false, link: '/Calls', created_date: minutesAgo(15) },
  { id: 'demo_notif_4', user_id: 'demo_user_admin', title: 'קריאה דחופה — תאונה', message: 'קריאה C-2026020116 — תאונה עם נפגעים, נדרש טיפול מיידי', type: 'error', related_entity_type: 'call', is_read: true, link: '/Calls', created_date: minutesAgo(12) },
  { id: 'demo_notif_5', user_id: 'demo_user_admin', title: 'קריאה הושלמה', message: 'קריאה C-2026020101 הושלמה בהצלחה', type: 'success', related_entity_type: 'call', is_read: true, link: '/Calls', created_date: daysAgo(5) },
  { id: 'demo_notif_6', user_id: 'demo_user_admin', title: 'חוזה קרוב לתפוגה', message: 'חוזה CON-2026-1003 של צמיגי השרון יפוג בקרוב', type: 'warning', related_entity_type: 'vendor', is_read: false, link: '/VendorContracts', created_date: daysAgo(1) },
  { id: 'demo_notif_7', user_id: 'demo_user_admin', title: 'ספק לא זמין', message: 'הספק מכונאי אקספרס סימן עצמו כלא זמין', type: 'warning', related_entity_type: 'vendor', is_read: true, link: '/ServiceProviders', created_date: hoursAgo(2) },
  { id: 'demo_notif_8', user_id: 'demo_user_admin', title: 'קריאה חדשה — בוט', message: 'קריאה C-2026020128 נכנסה דרך הבוט', type: 'info', related_entity_type: 'call', is_read: false, link: '/Calls', created_date: minutesAgo(0) },
];

// ===== USERS =====
const users = [
  { id: 'demo_user_admin', email: 'admin@natid-demo.com', full_name: 'אבי כהן', role: 'admin', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_user_admin2', email: 'admin2@natid-demo.com', full_name: 'רונית לוי', role: 'admin', is_active: true, created_date: daysAgo(300) },
  { id: 'demo_user_op1', email: 'operator1@natid-demo.com', full_name: 'שרה מזרחי', role: 'user', is_active: true, created_date: daysAgo(200) },
  { id: 'demo_user_op2', email: 'operator2@natid-demo.com', full_name: 'דוד פרץ', role: 'user', is_active: true, created_date: daysAgo(180) },
  { id: 'demo_user_op3', email: 'operator3@natid-demo.com', full_name: 'מיכל ביטון', role: 'user', is_active: true, created_date: daysAgo(150) },
  { id: 'demo_user_vendor1', email: 'vendor1@natid-demo.com', full_name: 'יוסי כהן', role: 'vendor', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_user_vendor2', email: 'vendor2@natid-demo.com', full_name: 'דוד לוי', role: 'vendor', is_active: true, created_date: daysAgo(400) },
  { id: 'demo_user_agent1', email: 'agent1@natid-demo.com', full_name: 'עומר דהן', role: 'user', is_active: true, created_date: daysAgo(100) },
];

// ===== MESSAGES =====
const messages = [
  { id: 'demo_msg_1', call_id: 'demo_call_11', sender_id: 'operator1@natid-demo.com', message_text: 'שלום, קריאה חדשה שובצה אליך', created_date: hoursAgo(1) },
  { id: 'demo_msg_2', call_id: 'demo_call_11', sender_id: 'demo_vendor_2', message_text: 'קיבלתי, יוצא לדרך', created_date: minutesAgo(55) },
  { id: 'demo_msg_3', call_id: 'demo_call_11', sender_id: 'demo_vendor_2', message_text: 'הגעתי למיקום, מתחיל אבחון', created_date: minutesAgo(30) },
  { id: 'demo_msg_4', call_id: 'demo_call_14', sender_id: 'operator1@natid-demo.com', message_text: 'קריאה דחופה — מצבר ישן, אנא הגע בהקדם', created_date: minutesAgo(15) },
  { id: 'demo_msg_5', call_id: 'demo_call_14', sender_id: 'demo_vendor_8', message_text: 'בדרך, צפי הגעה 10 דקות', created_date: minutesAgo(12) },
  { id: 'demo_msg_6', call_id: 'demo_call_16', sender_id: 'operator1@natid-demo.com', message_text: 'קריאה דחופה — תאונה עם נפגעים, נא לצאת מיד', created_date: minutesAgo(10) },
  { id: 'demo_msg_7', call_id: 'demo_call_16', sender_id: 'demo_vendor_1', message_text: 'יוצא עכשיו, צפי 5 דקות', created_date: minutesAgo(8) },
  { id: 'demo_msg_8', call_id: 'demo_call_2', sender_id: 'operator1@natid-demo.com', message_text: 'שלום, קריאה חדשה שובצה אליך', created_date: daysAgo(4) },
  { id: 'demo_msg_9', call_id: 'demo_call_2', sender_id: 'demo_vendor_1', message_text: 'קיבלתי, יוצא לדרך', created_date: daysAgo(4) },
  { id: 'demo_msg_10', call_id: 'demo_call_2', sender_id: 'demo_vendor_1', message_text: 'הגעתי, מתחיל גרירה', created_date: daysAgo(4) },
  { id: 'demo_msg_11', call_id: 'demo_call_2', sender_id: 'demo_vendor_1', message_text: 'גרירה הושלמה בהצלחה', created_date: daysAgo(4) },
  { id: 'demo_msg_12', call_id: 'demo_call_15', sender_id: 'operator2@natid-demo.com', message_text: 'ספק שובץ — דליפת שמן', created_date: minutesAgo(10) },
  { id: 'demo_msg_13', call_id: 'demo_call_15', sender_id: 'demo_vendor_2', message_text: 'בדרך, 15 דקות', created_date: minutesAgo(8) },
  { id: 'demo_msg_14', call_id: 'demo_call_12', sender_id: 'operator1@natid-demo.com', message_text: 'שובצת לקריאה — פנצ\'ר באשדוד', created_date: minutesAgo(45) },
  { id: 'demo_msg_15', call_id: 'demo_call_12', sender_id: 'demo_vendor_8', message_text: 'הגעתי, מטפל', created_date: minutesAgo(20) },
];

// ===== ROLES =====
const roles = [
  { id: 'demo_role_admin', name: 'admin', display_name: 'מנהל', permissions: { calls: { view: true, create: true, edit: true, delete: true, assign: true }, vendors: { view: true, create: true, edit: true, delete: true, manage_contracts: true }, customers: { view: true, create: true, edit: true, delete: true }, reports: { view: true, export: true, financial: true, performance: true, historical: true }, system: { users: true, roles: true, settings: true, automations: true, integrations: true, audit_log: true }, monitoring: { live_map: true, tracking: true, queue: true } }, created_date: daysAgo(365) },
  { id: 'demo_role_operator', name: 'operator', display_name: 'מוקדן', permissions: { calls: { view: true, create: true, edit: true, delete: false, assign: true }, vendors: { view: true, create: true, edit: true, delete: false, manage_contracts: true }, customers: { view: true, create: true, edit: true, delete: false }, reports: { view: true, export: true, financial: false, performance: true, historical: true }, system: { users: false, roles: false, settings: true, automations: true, integrations: false, audit_log: false }, monitoring: { live_map: true, tracking: true, queue: true } }, created_date: daysAgo(365) },
  { id: 'demo_role_agent', name: 'agent', display_name: 'טכנאי', permissions: { calls: { view: true, create: false, edit: false, delete: false, assign: false }, vendors: { view: false }, customers: { view: false }, reports: { view: false }, system: {}, monitoring: { queue: false } }, created_date: daysAgo(365) },
  { id: 'demo_role_vendor', name: 'vendor', display_name: 'ספק', permissions: { calls: { view: true }, vendors: { view: true }, customers: { view: false }, reports: { view: false }, system: {}, monitoring: {} }, created_date: daysAgo(365) },
];

// ===== USER PERMISSIONS =====
const userPermissions = [
  { id: 'demo_perm_1', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', role_name: 'מנהל', role_id: 'demo_role_admin', created_date: daysAgo(365) },
  { id: 'demo_perm_2', user_id: 'demo_user_op1', user_email: 'operator1@natid-demo.com', role_name: 'מוקדן', role_id: 'demo_role_operator', created_date: daysAgo(200) },
];

// ===== AUDIT LOG =====
const auditLog = [
  { id: 'demo_audit_1', action: 'create', entity_type: 'Call', entity_id: 'demo_call_24', entity_name: 'C-2026020124', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'נוצרה קריאה חדשה', severity: 'info', timestamp: minutesAgo(3), created_date: minutesAgo(3) },
  { id: 'demo_audit_2', action: 'assign', entity_type: 'Call', entity_id: 'demo_call_16', entity_name: 'C-2026020116', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'שובץ ספק: גרר המרכז — יוסי כהן', severity: 'info', timestamp: minutesAgo(8), created_date: minutesAgo(8) },
  { id: 'demo_audit_3', action: 'status_change', entity_type: 'Call', entity_id: 'demo_call_11', entity_name: 'C-2026020111', user_id: 'demo_user_op1', user_email: 'operator1@natid-demo.com', user_name: 'שרה מזרחי', user_role: 'operator', details: 'סטטוס שונה ל-in_progress', severity: 'info', timestamp: minutesAgo(30), created_date: minutesAgo(30) },
  { id: 'demo_audit_4', action: 'update', entity_type: 'Vendor', entity_id: 'demo_vendor_6', entity_name: 'מכונאי אקספרס — גיל אברהם', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'זמינות שונתה ל-offline', severity: 'warning', timestamp: hoursAgo(2), created_date: hoursAgo(2) },
  { id: 'demo_audit_5', action: 'create', entity_type: 'Customer', entity_id: 'demo_customer_8', entity_name: 'ישראל ישראלי', user_id: 'demo_user_op1', user_email: 'operator1@natid-demo.com', user_name: 'שרה מזרחי', user_role: 'operator', details: 'נוצר לקוח חדש', severity: 'info', timestamp: daysAgo(30), created_date: daysAgo(30) },
  { id: 'demo_audit_6', action: 'status_change', entity_type: 'Call', entity_id: 'demo_call_1', entity_name: 'C-2026020101', user_id: 'demo_user_op1', user_email: 'operator1@natid-demo.com', user_name: 'שרה מזרחי', user_role: 'operator', details: 'קריאה הושלמה', severity: 'info', timestamp: daysAgo(5), created_date: daysAgo(5) },
  { id: 'demo_audit_7', action: 'permission_change', entity_type: 'UserPermission', entity_name: 'operator3@natid-demo.com', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'תפקיד שונה', severity: 'warning', timestamp: daysAgo(10), created_date: daysAgo(10) },
  { id: 'demo_audit_8', action: 'export', entity_type: 'Report', entity_name: 'דוח תפעולי', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'יוצא דוח תפעולי ל-CSV', severity: 'info', timestamp: daysAgo(3), created_date: daysAgo(3) },
  { id: 'demo_audit_9', action: 'seed_demo_data', entity_type: 'System', entity_name: 'Demo Data Seed', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'נטענו נתוני דמו', severity: 'info', timestamp: daysAgo(30), created_date: daysAgo(30) },
  { id: 'demo_audit_10', action: 'create', entity_type: 'Vendor', entity_id: 'demo_vendor_10', entity_name: 'טכנו-גרר — תמר רוזנברג', user_id: 'demo_user_admin', user_email: 'admin@natid-demo.com', user_name: 'אבי כהן', user_role: 'admin', details: 'נוסף ספק חדש', severity: 'info', timestamp: daysAgo(45), created_date: daysAgo(45) },
];

// ===== PRODUCTS =====
const products = [
  { id: 'demo_product_1', name: 'גרירה רגילה', description: 'גרירת רכב פרטי עד 20 ק"מ', price: 350, category: 'tow_service', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_product_2', name: 'גרירה ארוכה', description: 'גרירת רכב פרטי מעל 20 ק"מ', price: 550, category: 'tow_service', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_product_3', name: 'החלפת גלגל', description: 'החלפת גלגל במקום כולל חומרים', price: 200, category: 'tire_service', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_product_4', name: 'התנעת מצבר', description: 'התנעה או החלפת מצבר', price: 180, category: 'battery_service', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_product_5', name: 'פתיחת רכב נעול', description: 'פתיחת רכב ללא נזק', price: 250, category: 'locksmith_service', is_active: true, created_date: daysAgo(365) },
  { id: 'demo_product_6', name: 'תידלוק במקום', description: 'אספקת 10 ליטר דלק', price: 150, category: 'fuel_service', is_active: true, created_date: daysAgo(365) },
];

// ===== FLEET =====
const fleet = [
  { id: 'demo_fleet_1', vehicle_number: 'GRR-001', vehicle_type: 'tow_truck', name: 'גרר מספר 1', status: 'active', area: 'center', assigned_vendor_id: 'demo_vendor_1', created_date: daysAgo(365) },
  { id: 'demo_fleet_2', vehicle_number: 'GRR-002', vehicle_type: 'tow_truck', name: 'גרר מספר 2', status: 'active', area: 'north', assigned_vendor_id: 'demo_vendor_5', created_date: daysAgo(300) },
  { id: 'demo_fleet_3', vehicle_number: 'MOB-001', vehicle_type: 'mobile_unit', name: 'ניידת שירות 1', status: 'active', area: 'center', assigned_vendor_id: 'demo_vendor_2', created_date: daysAgo(250) },
  { id: 'demo_fleet_4', vehicle_number: 'GRR-003', vehicle_type: 'tow_truck', name: 'גרר מספר 3', status: 'maintenance', area: 'south', assigned_vendor_id: null, created_date: daysAgo(200) },
];

// ===== ASSIGNMENT ATTEMPTS =====
const assignmentAttempts = [
  { id: 'demo_attempt_1', call_id: 'demo_call_2', vendor_id: 'demo_vendor_1', status: 'accepted', score: 92, distance_km: 5, response_time_seconds: 30, expires_at: daysFromNow(1), created_date: daysAgo(4) },
  { id: 'demo_attempt_2', call_id: 'demo_call_2', vendor_id: 'demo_vendor_8', status: 'declined', score: 78, distance_km: 15, decline_reason: 'מרחק רחוק מדי', response_time_seconds: 60, expires_at: daysAgo(4), created_date: daysAgo(4) },
  { id: 'demo_attempt_3', call_id: 'demo_call_5', vendor_id: 'demo_vendor_1', status: 'accepted', score: 88, distance_km: 8, response_time_seconds: 15, expires_at: daysFromNow(1), created_date: daysAgo(2) },
  { id: 'demo_attempt_4', call_id: 'demo_call_11', vendor_id: 'demo_vendor_2', status: 'accepted', score: 95, distance_km: 7, response_time_seconds: 20, expires_at: daysFromNow(1), created_date: hoursAgo(1) },
  { id: 'demo_attempt_5', call_id: 'demo_call_14', vendor_id: 'demo_vendor_8', status: 'accepted', score: 90, distance_km: 10, response_time_seconds: 25, expires_at: daysFromNow(1), created_date: minutesAgo(15) },
  { id: 'demo_attempt_6', call_id: 'demo_call_16', vendor_id: 'demo_vendor_1', status: 'accepted', score: 85, distance_km: 3, response_time_seconds: 10, expires_at: daysFromNow(1), created_date: minutesAgo(8) },
  { id: 'demo_attempt_7', call_id: 'demo_call_17', vendor_id: 'demo_vendor_4', status: 'accepted', score: 82, distance_km: 8, response_time_seconds: 45, expires_at: daysFromNow(1), created_date: minutesAgo(5) },
  { id: 'demo_attempt_8', call_id: 'demo_call_11', vendor_id: 'demo_vendor_8', status: 'declined', score: 72, distance_km: 20, decline_reason: 'עסוק בקריאה אחרת', response_time_seconds: 90, expires_at: hoursAgo(1), created_date: hoursAgo(2) },
];

// ===== CUSTOMER INTERACTIONS =====
const customerInteractions = [
  { id: 'demo_interaction_1', customer_id: 'demo_customer_1', interaction_type: 'call', description: 'שיחת שירות — בירור לגבי קריאה C-2026020101', created_by: 'operator1@natid-demo.com', interaction_date: daysAgo(5), created_date: daysAgo(5) },
  { id: 'demo_interaction_2', customer_id: 'demo_customer_2', interaction_type: 'email', description: 'שליחת סיכום חודשי ללקוח', created_by: 'admin@natid-demo.com', interaction_date: daysAgo(10), created_date: daysAgo(10) },
  { id: 'demo_interaction_3', customer_id: 'demo_customer_5', interaction_type: 'call', description: 'תיאום תנאי חוזה חדש', created_by: 'admin@natid-demo.com', interaction_date: daysAgo(15), created_date: daysAgo(15) },
  { id: 'demo_interaction_4', customer_id: 'demo_customer_3', interaction_type: 'meeting', description: 'פגישת סקירה רבעונית', created_by: 'admin@natid-demo.com', interaction_date: daysAgo(30), created_date: daysAgo(30) },
  { id: 'demo_interaction_5', customer_id: 'demo_customer_4', interaction_type: 'call', description: 'תלונה על זמן המתנה — קריאה C-2026020104', created_by: 'operator2@natid-demo.com', interaction_date: daysAgo(3), created_date: daysAgo(3) },
  { id: 'demo_interaction_6', customer_id: 'demo_customer_8', interaction_type: 'call', description: 'לקוח חדש — רישום ראשוני', created_by: 'operator1@natid-demo.com', interaction_date: daysAgo(30), created_date: daysAgo(30) },
];

// ===== CASES =====
const cases = [
  { id: 'demo_case_1', call_id: 'demo_call_5', case_number: 'CASE-2026-001', case_status: 'closed', description: 'תאונה — נדרש תיעוד ופיצוי', assignee: 'admin@natid-demo.com', priority: 'critical', created_date: daysAgo(2) },
  { id: 'demo_case_2', call_id: 'demo_call_16', case_number: 'CASE-2026-002', case_status: 'open', description: 'תאונה עם נפגעים — מעקב רפואי', assignee: 'operator1@natid-demo.com', priority: 'critical', created_date: minutesAgo(12) },
  { id: 'demo_case_3', call_id: 'demo_call_8', case_number: 'CASE-2026-003', case_status: 'closed', description: 'בעיה חוזרת — רכב לא מתניע', assignee: 'operator2@natid-demo.com', priority: 'normal', created_date: daysAgo(8) },
  { id: 'demo_case_4', call_id: 'demo_call_23', case_number: 'CASE-2026-004', case_status: 'open', description: 'פגע וברח — נדרש דוח משטרה', assignee: 'admin@natid-demo.com', priority: 'urgent', created_date: minutesAgo(5) },
  { id: 'demo_case_5', call_id: 'demo_call_9', case_number: 'CASE-2026-005', case_status: 'in_progress', description: 'תביעה מלקוח — זמן המתנה ארוך', assignee: 'admin@natid-demo.com', priority: 'normal', created_date: daysAgo(9) },
];

// ===== CASE ACTIVITIES =====
const caseActivities = [
  { id: 'demo_ca_1', case_id: 'demo_case_1', activity_type: 'created', description: 'תיק נפתח — תאונה קלה', created_by: 'admin@natid-demo.com', created_date: daysAgo(2) },
  { id: 'demo_ca_2', case_id: 'demo_case_1', activity_type: 'note', description: 'נשלח דוח תאונה לחברת ביטוח', created_by: 'admin@natid-demo.com', created_date: daysAgo(1) },
  { id: 'demo_ca_3', case_id: 'demo_case_1', activity_type: 'status_change', description: 'תיק נסגר — פיצוי אושר', created_by: 'admin@natid-demo.com', created_date: hoursAgo(5) },
  { id: 'demo_ca_4', case_id: 'demo_case_2', activity_type: 'created', description: 'תיק נפתח — תאונה עם נפגעים', created_by: 'operator1@natid-demo.com', created_date: minutesAgo(12) },
  { id: 'demo_ca_5', case_id: 'demo_case_2', activity_type: 'note', description: 'נדרש מעקב רפואי עבור הנפגעים', created_by: 'operator1@natid-demo.com', created_date: minutesAgo(8) },
  { id: 'demo_ca_6', case_id: 'demo_case_4', activity_type: 'created', description: 'תיק נפתח — פגע וברח', created_by: 'admin@natid-demo.com', created_date: minutesAgo(5) },
  { id: 'demo_ca_7', case_id: 'demo_case_5', activity_type: 'created', description: 'תביעת לקוח — זמן המתנה חורג מ-SLA', created_by: 'admin@natid-demo.com', created_date: daysAgo(9) },
  { id: 'demo_ca_8', case_id: 'demo_case_5', activity_type: 'note', description: 'מנהל שוחח עם הלקוח, הוצע פיצוי', created_by: 'admin@natid-demo.com', created_date: daysAgo(7) },
];

// ===== VENDOR PRICING =====
const vendorPricing = [
  { id: 'demo_pricing_1', vendor_id: 'demo_vendor_1', service_type: 'tow_truck', area: 'center', price: 350, agreement_start: daysAgo(180), agreement_end: daysFromNow(185), is_active: true, created_date: daysAgo(180) },
  { id: 'demo_pricing_2', vendor_id: 'demo_vendor_2', service_type: 'mechanic', area: 'center', price: 280, agreement_start: daysAgo(200), agreement_end: daysFromNow(165), is_active: true, created_date: daysAgo(200) },
  { id: 'demo_pricing_3', vendor_id: 'demo_vendor_3', service_type: 'tire_service', area: 'sharon', price: 200, agreement_start: daysAgo(30), agreement_end: daysFromNow(0), is_active: true, created_date: daysAgo(30) },
  { id: 'demo_pricing_4', vendor_id: 'demo_vendor_7', service_type: 'tow_truck', area: 'south', price: 450, agreement_start: daysAgo(90), agreement_end: daysFromNow(275), is_active: true, created_date: daysAgo(90) },
  { id: 'demo_pricing_5', vendor_id: 'demo_vendor_9', service_type: 'tow_truck', area: 'jerusalem', price: 380, agreement_start: daysAgo(250), agreement_end: daysFromNow(115), is_active: true, created_date: daysAgo(250) },
];

// ===== EMPTY ENTITIES =====
const callPhotos = [];
const notificationSettings = [];
const contracts = [];
const questionnaires = [];
const companies = [];

// ===== EXPORT =====
export const demoData = {
  customers,
  vendors,
  calls,
  workQueue,
  callHistory,
  callPhotos,
  vendorRatings,
  vendorPayments,
  vendorContracts,
  vendorLocations,
  vendorPricing,
  assignmentAttempts,
  notifications,
  notificationSettings,
  messages,
  cases,
  caseActivities,
  customerInteractions,
  users,
  roles,
  userPermissions,
  auditLog,
  products,
  fleet,
  contracts,
  questionnaires,
  companies,
};
